apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-persistent-storage # reference to "volumes".name
      mountPath: /data/redis
  volumes:
  - name: redis-persistent-storage
    emptyDir: {}
    # Creates a new directory that will exist as long as the Pod is running on the node, but it can persist across container failures and restarts.
    # hostPath
